version: '3'
services:
  db:
    image: postgres:9.6.3
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "2345:5432"
